apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-logs-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-secrets
  target:
    name: grafana-cloud-logs-credentials
  data:
    - secretKey: username
      remoteRef:
        key: GCLOUD_HOSTED_LOGS_ID
    - secretKey: password
      remoteRef:
        key: GCLOUD_API_TOKEN
