apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-logs-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-secrets
  target:
    name: grafana-cloud-logs-credentials
  data:
    - secretKey: GRAFANA_CLOUD_LOGS_USERNAME
      remoteRef:
        key: username
    - secretKey: GCLOUD_KUBERNETES_RW_TOKEN
      remoteRef:
        key: password
