cluster:
  name: default
infisical:
  endpoint: https://eu.infisical.com
  environment: dev
  project: terraforge-u8-js
image:
  repository: hashicorp/http-echo
  tag: '1.0'
  pullPolicy: IfNotPresent
replicaCount: 1
ingress:
  enabled: false
  host: echo.lke-demo.zuse.systems
