apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ngrok-operator-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-secrets
  target:
    name: ngrok-operator-credentials
  data:
    - secretKey: API_KEY
      remoteRef:
        key: NGROK_API_KEY
    - secretKey: AUTHTOKEN
      remoteRef:
        key: NGROK_AUTH_TOKEN
