apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infra-secrets
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: universal-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: universal-auth-credentials
      secretsScope:
        projectSlug: terraforge-u8-js
        environmentSlug: dev
