---
# helm/prometheus.yaml
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: cluster-issuer
    hosts:
      - prometheus.k3s-lab.local
    tls:
      - secretName: prometheus-server-tls
        hosts:
          - prometheus.k3s-lab.local
