apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infra-secrets
spec:
  provider:
    infisical:
      hostAPI: '{{ .Values.infisical.endpoint }}'
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: universal-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: universal-auth-credentials
      secretsScope:
        projectSlug: '{{ .Values.infisical.project }}'
        environmentSlug: '{{ .Values.infisical.environment }}'
